[package]
name = "mcuboot-img-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
hex = "0.4.3"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
